apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-agent
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  # TODO(muvaf): This part needs to be dynamic.
  - apiGroups: ["common.crossplane.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-agent
subjects:
  - kind: ServiceAccount
    name: crossplane-agent
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: crossplane-agent
  apiGroup: rbac.authorization.k8s.io